name: 'Smart Lab'
description: 'This is the official web page for the Smart Lab at HKUST.'

url: 'https://hkustsmartlab.github.io/'

paginate: 5
plugins: [jekyll-paginate]
paginate_path: 'news/page:num'

permalink: pretty
markdown: kramdown
kramdown:
    parse_block_html: true

include:
  - "_next"
  - "showcase/PathBench/_next"
  - "showcase/PathBench/_next/**/*"

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

collections:
    affiliates:
        output: true
    members:
        output: true
    publications:
        output: true
    visitors:
        output: true
    undergrads:
        output: true
